config/routes.rb
Rails.application.routes.draw do
  
    root to: 'sessions#new'
    resources :users
    resources :locations
    resources :timetracks
    resources :sessions
    get 'index', to: 'timetracks#index'
    get 'account', to: 'users#edit'
    get 'login', to: 'sessions#new'
    get 'signup', to: 'users#new'
    get 'offices', to: 'locations#index'
    get 'office', to: 'locations#new'
    get 'savepoint', to: 'timetracks#new'
    delete 'logout', to: 'sessions#destroy'
    post 'login', to: 'sessions#create'
    get 'map', to: 'locations#map'

end

app/models/timetrack.rb
class Timetrack < ApplicationRecord
  belongs_to :user


 
end

app/controllers/timetracks_controller.rb
class TimetracksController < ApplicationController
  before_action :set_timetrack, only: [:show, :edit, :update, :destroy]
  before_action :require_logged_in_user
    # GET /timetracks
  # GET /timetracks.json
  def index

    if  params[:search].present?
      @search = params[:search]
      @timetracks = Timetrack.where("id = :search OR user_id = :search", search: "#{@search}")
    
    else 
       @timetracks = Timetrack.all
     end
    
  end
   
  
  # GET /timetracks/1
  # GET /timetracks/1.json
  def show
  end

  # GET /timetracks/new
  def new
    @timetrack = Timetrack.new
  end

  # GET /timetracks/1/edit
  def edit
  end

  # POST /timetracks
  # POST /timetracks.json
  def create
    @timetrack = Timetrack.new(timetrack_params)

    respond_to do |format|
      if @timetrack.save
        format.html { redirect_to @timetrack, success: 'Savepoint was successfully created.'}
        format.json { render :show, status: :created, timetrack: @timetrack }
      else
        format.html { render :new }
        format.json { render json: @timetrack.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /timetracks/1
  # PATCH/PUT /timetracks/1.json
  def update
    respond_to do |format|
      if @timetrack.update(timetrack_params)
        format.html { redirect_to @timetrack, success: 'Savepoint was successfully created.'}
        format.json { render :show, status: :ok, timetrack: @timetrack }
      else
        format.html { render :edit }
        format.json { render json: @timetrack.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /timetracks/1
  # DELETE /timetracks/1.json
  def destroy
    @timetrack.destroy
    respond_to do |format|
      redirect_to @timetrack, warning: 'Guess you destroyed it.'
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_timetrack
      @timetrack = Timetrack.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def timetrack_params
    @user = current_user.id
      params.require(:timetrack).permit(:longitude, :latitude, :comment , :user_id)
    end
end

app/helpers/timetracks_helper.rb
module TimetracksHelper

	def ttToJson
		@timetracks = Timetrack.all.as_json.to_json
				
	end
end

app/views/timetracks/_form.html.erb
<p id="notice"><%= notice %></p>
<% provide :head_tags do %>
<meta name='turbolinks-visit-control' content='reload'>
<script>
document.addEventListener("DOMContentLoaded", function() {
    var locations = <%= raw locToJson %> ;
    initMap2(locations);
    startTime();

});
</script>
<% end %>
<div id="clock" class="clock"></div>
<%= form_with(model: timetrack, local: true) do |form| %>
<br>
<div class="fox">
    <h1>Savepoint</h1>
    <%= form.label :address %> <br>
    <%= form.text_field :address, {id: 'address', placeholder: 'Type an address'} %> <br>
    <%= form.label :latitude %> <br>
    <%= form.text_field :latitude, {id: 'latitude' } %> <br>
    <%= form.label :longitude%> <br>
    <%= form.text_field :longitude, {id: 'longitude' }%> <br>
    <%= form.label :'Any comments?' %> <br>
    <%= form.text_field :comment %> <br>
    <%= form.label :'Your ID' %> <br>
    <%= form.text_field :user_id, :value => current_user.id, :readonly => true %>
    <div class="map" id="map2"></div>
    <%= form.submit id: "submit" %>
</div>
<% end %>

app/views/timetracks/_show.html.erb
<p id="notice"><%= notice %> </p>  
<div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"> Detailed timetrack #<%= @timetrack.id %> </h5>
   </div>     
        <div class="modal-body">
    <p>
    <strong>User name: </strong>
     <%= @timetrack.user.name %>
</p>
<p>
    <strong>User commentary: </strong>
    <%= @timetrack.comment %>
</p>
<p>
    <strong>Address: </strong>
    <span id="address"></span>
</p>
<p>
    <strong>Longitude:</strong>
    <%= @timetrack.longitude %>
</p>
<p>
    <strong>Latitude:</strong>
    <%= @timetrack.latitude %>
</p>
<p>
    <strong>This happend on: </strong>
    <%= @timetrack.created_at %>
</p>
      <div id="map" class="map"> </div> 
    
 </div> 
 <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
      </div>

app/views/timetracks/edit.html.erb
<%= render 'form', timetrack: @timetrack %>

app/views/timetracks/index.html.erb
<p id="notice">
    <%= notice %>
</p>
<h2>Welcome back,
    <%= current_user.name %>
</h2>
<div class="search">
    <%= form_tag( timetracks_path, :method => 'GET') do %>
    <strong> Specific ID or user? </strong>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag 'Search', name: nil %>
    <% end %>
</div>
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        </div>
    </div>
</div>
<table class="table table-striped table-dark">
    <thead>
        <tr>
            <th scope="col">#ID</th>
            <th scope="col">User ID</th>
            <th scope="col">Name </th>
            <th scope="col">Date</th>
            <th scope="col">Details </th>
        </tr>
    </thead>
    <tbody>
        <% @timetracks.each do |timetrack| %>
        <% if current_user.user_role != 1 && timetrack.user.id == current_user.id  %>
        <tr scope="row">
            <td>
                <%= timetrack.id%>
            </td>
            <td>
                <%= timetrack.user.id%>
            </td>
            <td>
                <%= timetrack.user.name %>
            </td>
            <td>
                <%= timetrack.user.created_at %>
            </td>
            <td>
                <%= link_to "Details", timetrack, :class => "btn btn-primary", :remote => true %>
            </td>
        </tr>
        <% end %>
        <% else 
      if current_user.user_role == 1 %>
        <tr scope="row">
            <td>
                <%= timetrack.id%>
            </td>
            <td>
                <%= timetrack.user.id%>
            </td>
            <td>
                <%= timetrack.user.name %>
            </td>
            <td>
                <%= timetrack.user.created_at %>
            </td>
            <td>
                <%= link_to "Details", timetrack,  :class => "btn btn-primary", :remote => true %>
            </td>
        </tr>
        <% end %>
        <% end %>
    </tbody>
</table>
<br>

app/views/timetracks/new.html.erb
<%= render 'form', timetrack: @timetrack %>

app/views/timetracks/show.html.erb
<% provide :head_tags do %>
<meta name='turbolinks-visit-control' content='reload'>
<script>
document.addEventListener("DOMContentLoaded", function() {
    initMap(<%=@timetrack.latitude%>, <%=@timetrack.longitude%>);
    parse_end(<%=@timetrack.latitude%>, <%=@timetrack.longitude%>);
});
</script>
<% end %>
<p id="notice"><%= notice %></p>
<p>
    <strong>User:</strong>
    <%= @timetrack.user.name %>
</p>
<p>
    <strong>User commentary: </strong>
    <%= @timetrack.comment %>
</p>
<p>
    <strong>Address: </strong>
    <span id="address"></span>
</p>
<p>
    <strong>Longitude:</strong>
    <%= @timetrack.longitude %>
</p>
<p>
    <strong>Latitude:</strong>
    <%= @timetrack.latitude %>
</p>
<p>
    <strong>This happend on: </strong>
    <%= @timetrack.created_at %>
</p>
<div class="map" id="map">
</div>

app/views/timetracks/show.js.erb
$("#modal").find(".modal-content").html("<%= j render 'show', timetrack: @timetrack %>");
initMap(<%=@timetrack.latitude%>, <%=@timetrack.longitude%>);
parse_end(<%=@timetrack.latitude%>, <%=@timetrack.longitude%>);
$("#modal").modal('show');