config/routes.rb
Rails.application.routes.draw do
  
    root to: 'sessions#new'
    resources :users
    resources :locations
    resources :timetracks
    resources :sessions
    get 'index', to: 'timetracks#index'
    get 'account', to: 'users#edit'
    get 'login', to: 'sessions#new'
    get 'signup', to: 'users#new'
    get 'offices', to: 'locations#index'
    get 'office', to: 'locations#new'
    get 'savepoint', to: 'timetracks#new'
    delete 'logout', to: 'sessions#destroy'
    post 'login', to: 'sessions#create'
    get 'map', to: 'locations#map'

end

app/models/location.rb
class Location < ApplicationRecord
  	belongs_to :user
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]
  before_action :require_logged_in_user
  # GET /locations
  # GET /locations.json

  def index
    if  params[:search].present?
      @search = params[:search]
      @locations = Location.where("id = :search OR user_id = :search", search: "#{@search}")
    else 
       @locations = Location.all
    end
  end


  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, success: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html {redirect_to @location, success: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
     redirect_to locations_url, warning: 'Location was successfully destroyed.' 
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:desc, :meters, :longitude, :latitude, :user_id)
    end
end

app/helpers/locations_helper.rb
module LocationsHelper
	def locToJson
		@locations = Location.all.as_json.to_json			
	end
	
end

app/views/locations/_form.html.erb
<p id="notice"><%= notice %></p>
<% provide :head_tags do %>
<meta name='turbolinks-visit-control' content='reload'>
<script>
document.addEventListener("DOMContentLoaded", function() {
    initMap2();

});
</script>
<% end %>
<%= form_with(model: location, local: true) do |form| %>
<div class="fox">
    <br><br><br><br><br>
    <h1>Workplaces</h1>
    <%= form.label :'Place Description'  %> <br>
    <%= form.text_field :desc %> <br>
    <%= form.label :'Address'  %> <br>
    <%= form.text_field :address, {id: 'address'} %> <br>
    <%= form.label :Meters %> <br>
    <%= form.number_field :meters %> <br>
    <%= form.label :latitude %> <br>
    <%= form.text_field :latitude, {id: 'latitude' }%> <br>
    <%= form.label :longitude %> <br>
    <%= form.text_field :longitude, {id: 'longitude' }%> <br>
    <%= form.label :'Your ID'%> <br>
    <%= form.text_field :user_id, :value => current_user.id, :readonly => true %><br>
    <div class="map" id="map2"></div>
    <%= form.submit %>
</div>
<% end %>

app/views/locations/_show.html.erb
<p id="notice"><%= notice %> </p>  
<div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"> Detailed Office #<%= @location.id %> </h5>
   </div>     
        <div class="modal-body">
<p>
    <strong>User:</strong>
    <%= @location.user.name %>
</p>
<p>
    <strong>Description:</strong>
    <%= @location.desc %>
</p>
<p>
    <strong>Address:</strong>
    <span id="address"></span>
</p>
<p>
    <strong>Meters:</strong>
    <%= @location.meters %>
</p>
<p>
    <strong>Longitude:</strong>
    <%= @location.longitude %>
</p>
<p>
    <strong>Latitude:</strong>
    <%= @location.latitude %>
</p>
      <div id="map" class="map"> </div> 
    
 </div> 
 <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
      </div>

app/views/locations/edit.html.erb
<%= render 'form', location: @location %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>
<div class="search">
<%= form_tag(locations_path, :method => 'GET') do %>
  <strong> Specific ID or user? </strong>
   <%= text_field_tag :search, params[:search] %>
  <%= submit_tag 'Search', name: nil %>
<% end %>
</div>
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        </div>
    </div>
</div>
<table class="table table-striped table-dark">
  <thead>
    <tr>
      <th>#ID</th>
      <th>User</th>
      <th>Description</th>
      <th>Details</th>
      <th>Edit</th>   
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.id %></td>
        <td><%= location.user.name %></td>
        <td><%= location.desc %></td>
        <td><%= link_to 'Details ', location, :class => "btn btn-primary", :remote => true %></td>
        <td><%= link_to 'Edit', edit_location_path(location), :class => "btn btn-info"  %></td>
  
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/locations/map.html.erb
<% provide :head_tags do %>
<meta name='turbolinks-visit-control' content='reload'>
<script>
document.addEventListener("DOMContentLoaded", function() {
	var locations = <%= raw locToJson %> ;
   	boundary(locations)
});
</script>
<%- end %>


    <div id="map" class="bigmap">
</div>

   

app/views/locations/new.html.erb
<%= render 'form', location: @location %>

app/views/locations/show.html.erb
<% provide :head_tags do %>
<meta name='turbolinks-visit-control' content='reload'>
<script>
document.addEventListener("DOMContentLoaded", function() {
    initMap(<%=@location.latitude%>, <%=@location.longitude%>);
    parse_end(<%=@location.latitude%>, <%=@location.longitude%>);
});
</script>
<% end %>
<p id="notice">
    <%= notice %>
</p>
<p>
    <strong>User:</strong>
    <%= @location.user.name %>
</p>
<p>
    <strong>Description:</strong>
    <%= @location.desc %>
</p>
<p>
    <strong>Address:</strong>
    <span id="address"></span>
</p>
<p>
    <strong>Meters:</strong>
    <%= @location.meters %>
</p>
<p>
    <strong>Longitude:</strong>
    <%= @location.longitude %>
</p>
<p>
    <strong>Latitude:</strong>
    <%= @location.latitude %>
</p>
<div id="map" class="map">
</div>

app/views/locations/show.js.erb
$("#modal").find(".modal-content").html("<%= j render 'show', location: @location %>");
initMap(<%=@location.latitude%>, <%=@location.longitude%>);
parse_end(<%=@location.latitude%>, <%=@location.longitude%>);
$("#modal").modal('show');